#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <iostream>
#include <cmath>

using namespace std;

class Complex         
{
private:
  double deist, mnim;     

public:
  // конструкторы 

  Complex () // autogenerated
  {
  };

  Complex (double d)   
  {
    deist = d;
    mnim = 0;
  }

  Complex (double d, double m)
  {
    deist = d;
    mnim = m;
  }

  Complex (const Complex &c)  // autogenerated
  {
    deist = c.deist;
    mnim = c.mnim;
  }

  ~Complex () // autogenerated
  {
  }

  double abs ()  // зачем?      
  {
    return sqrt (deist * deist + mnim * mnim);
  }

  Complex& operator = (Complex &c)  // autogenerated, const param 
  {
    deist = c.deist;
    mnim = c.mnim;

    return (*this);
  }

  Complex operator + (const Complex &c)   // const
  {
    return Complex (deist + c.deist, mnim + c.mnim);
  }

  Complex operator - (const Complex &c)   // const
  {
    return Complex(deist - c.deist, mnim - c.mnim);
  }

  Complex operator * (const Complex &c)   // const
  {
    return Complex(deist * c.deist - mnim * c.mnim, deist * c.mnim + mnim * c.deist);
  }

  Complex operator / (const Complex &c)   // const
  {
    Complex temp;

    double r = c.deist * c.deist + c.mnim * c.mnim;
    temp.re = (deist * c.deist + mnim * c.mnim) / d;
    temp.im = (mnim * c.deist - deist * c.mnim) / d;

    return temp;
  }

  friend ostream & operator<< (ostream &, const Complex &);   
  friend istream & operator>> (istream &, Complex &);         

};

ostream& operator<< (ostream &out, const Complex &c)
{
  out << "(" << c.deist << ", " << c.mnim << ")";
  return out;
}

istream& operator>> (istream &in, Complex &c) // ввод должен соответствовать выводу
{
  in >> c.deist >> c.mnim;
  return in;
}

int
main ()
{
  Complex a (3, 2);
  Complex b (1, -); // работает?

  cout << "a = " << a << "; b =" << b << endl;

  a += b;
 
  cout << "a = " << a << "; b =" << b << endl;

  Complex c = a + b;

  cout << c << endl;
  cout << a + b << endl;
  cout << a * b << endl;

  return 0;
}

